# Generated by Django 4.1.6 on 2023-02-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="first_name", new_name="firstname",
        ),
        migrations.RenameField(
            model_name="employee", old_name="last_name", new_name="lastname",
        ),
    ]
