# Generated by Django 4.1.6 on 2023-02-11 06:05

import django.core.validators
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("team_management", "0004_rename_employee_member"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="salary",),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                max_length=200,
                unique=True,
                validators=[django.core.validators.EmailValidator],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
